kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ .Values.pvc.name }}
  labels:
    app: {{ .Values.pvc.labels.app }}
  annotations:
    cdi.kubevirt.io/storage.import.endpoint: {{ .Values.pvc.image | quote }}
    "helm.sh/hook": post-install
    "helm.sh/hook-weight": "0"
    "helm.sh/hook-delete-policy": hook-succeeded
 spec:
  accessModes:
  - {{ .Values.pvc.accessModes }}
  resources:
    requests:
      storage: {{ .Values.pvc.storageSize }}
