apiVersion: kubevirt.io/v1alpha3
kind: VirtualMachineInstance
metadata:
  namespace: {{ .Values.kubevirt.namespace }}
  name: {{ .Values.kubevirt.name }} 
  labels:
      kubevirt.io/size: {{ .Values.kubevirt.labels.size }}
      kubevirt.io/domain: {{ .Values.kubevirt.labels.domain }}
spec:
  terminationGracePeriodSeconds: 5
  domain:
    resources:
      requests:
        memory: {{ .Values.kubevirt.memory }}
        cpu: {{ .Values.kubevirt.cpu }}
    devices:
      disks:
      - name: containerdisk
        disk:
          bus: virtio
      - name: cloudinitdisk
        disk:
          bus: virtio
  volumes:
    - name: containerdisk
      containerDisk:
        image: {{ .Values.kubevirt.storage.image }}
    - name: cloudinitdisk
      cloudInitNoCloud: 
        userDataBase64: {{ .Values.kubevirt.storage.cloud.init }} 
